version: '2'
services:
  nginx:
    image: "nginx"
    ports:
      - "80:80"
    volumes:
      - ./etc/nginx:/etc/nginx
      - ./app/web:/app/web
    links:
      - php7-fpm:php-fpm
    depends_on:
      - php7-fpm
  php7-fpm:
    image: "helloxiaoxin/php-drupal:7.1-oci8-xdebug"
    volumes:
      - ./app/web:/app/web
      - ./etc/php:/usr/local/etc
    depends_on:
      - mariadb
      - memcached
      - redis
    links:
      - mariadb:mysql
      - memcached:memcached
      - redis:redis
  mariadb:
    image: mariadb
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb-data:/var/lib/mysql
      - ./etc/mariadb/conf.d:/etc/mysql/conf.d
      - ./etc/mariadb/my.cnf:/etc/mysql/my.cnf
    environment:
      TZ: 'Asia/Shanghai'
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: "%"
  memcached:
    image: memcached
    mem_limit: 256M
  redis:
    image: redis
  dnsmasq:
    image: "andyshinn/dnsmasq:latest"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    cap_add:
      - NET_ADMIN
    volumes:
      - ./etc/dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf
